using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security;
using System.Text;

namespace DeusaldLocalizerCommon
{
    /// <summary>
    /// Exports localization keys and their translations to a single auto-generated C# file.
    ///
    /// The output is one wrapping <c>static class</c> (name chosen by the caller) that contains:
    ///   • a nested static-class tree mirroring the category path of every exported key, where each
    ///     key is a <c>public static readonly Guid</c> field named after the key (so callers can
    ///     reference an id as e.g. <c>ClassName.UI.Buttons.play</c>) documented with its description;
    ///   • a <c>Dictionary&lt;string, Dictionary&lt;Guid, string&gt;&gt; Translations</c> (language → keyId → text)
    ///     holding every exported translation;
    ///   • a <c>Get(language, keyId, values)</c> lookup that returns the translation and, when values are
    ///     supplied, renders them through SmartFormat.
    ///
    /// Reuses <see cref="LocalizationExportService"/>'s key filter, key ordering and language ordering
    /// so a C# export selects exactly the same keys/languages as the equivalent Excel export.
    /// </summary>
    public static class CSharpExportService
    {
        private const string _INDENT = "    ";

        // Names the wrapper class reserves for its own members; a category/key that collides is renamed.
        private static readonly HashSet<string> _ReservedRootNames = new HashSet<string>(StringComparer.Ordinal)
        {
            "Translations", "Get",
        };

        /// <summary>
        /// Renders the export as C# source text.
        /// </summary>
        /// <param name="project">The project whose keys/translations are exported.</param>
        /// <param name="className">Name of the generated wrapper class (sanitized to a valid identifier).</param>
        /// <param name="namespaceName">Optional namespace to wrap the class in; null/blank emits no namespace.</param>
        /// <param name="options">Optional flag/tag/language filter, shared with the Excel export.</param>
        public static string ExportToString(LocProject project, string className, string? namespaceName = null,
                                            LocExportOptions? options = null)
        {
            string safeClass = SanitizeIdentifier(className, "Localization");
            string? safeNs   = string.IsNullOrWhiteSpace(namespaceName) ? null : SanitizeNamespace(namespaceName!);

            List<string>             languages    = LocalizationExportService.BuildLanguageList(project, options);
            List<LocLocalizationKey> exportedKeys = OrderedExportedKeys(project, options);

            StringBuilder sb = new StringBuilder();
            AppendHeader(sb, safeClass);

            sb.Append("using System;\n");
            sb.Append("using System.Collections.Generic;\n");
            sb.Append("using SmartFormat;\n\n");
            sb.Append("#nullable enable\n\n");

            int classLevel = safeNs == null ? 0 : 1;
            if (safeNs != null)
            {
                sb.Append("namespace ").Append(safeNs).Append('\n');
                sb.Append("{\n");
            }

            string classIndent = Indent(classLevel);
            sb.Append(classIndent).Append("public static class ").Append(safeClass).Append('\n');
            sb.Append(classIndent).Append("{\n");

            // ── Key-id class tree ───────────────────────────────────────────
            Node root = BuildTree(project, exportedKeys);
            AppendNode(sb, root, classLevel + 1, seedReserved: true);

            // ── Translations dictionary ─────────────────────────────────────
            sb.Append('\n');
            AppendTranslations(sb, classLevel + 1, languages, exportedKeys, project);

            // ── Lookup method ───────────────────────────────────────────────
            sb.Append('\n');
            AppendGetMethod(sb, classLevel + 1);

            sb.Append(classIndent).Append("}\n");
            if (safeNs != null)
                sb.Append("}\n");

            return sb.ToString();
        }

        /// <summary>The sanitized class name, suitable as the base of the generated file's name.</summary>
        public static string ClassFileName(string className) => SanitizeIdentifier(className, "Localization");

        private static void AppendHeader(StringBuilder sb, string className)
        {
            sb.Append("// ------------------------------------------------------------------------------\n");
            sb.Append("// <auto-generated>\n");
            sb.Append("//     This code was generated automatically by Deusald Localizer.\n");
            sb.Append("//     Any changes made to this file may be lost when it is regenerated.\n");
            sb.Append("//\n");
            sb.Append("//     '").Append(className).Append(".Get' formats values through SmartFormat, so the\n");
            sb.Append("//     consuming project must reference the SmartFormat NuGet package.\n");
            sb.Append("// </auto-generated>\n");
            sb.Append("// ------------------------------------------------------------------------------\n\n");
        }

        private static void AppendNode(StringBuilder sb, Node node, int level, bool seedReserved)
        {
            string indent = Indent(level);

            // Reserve names taken by the wrapper's own members at the top level so a category/key
            // named "Translations"/"Get" is renamed instead of clashing.
            HashSet<string> used = seedReserved
                                       ? new HashSet<string>(_ReservedRootNames, StringComparer.Ordinal)
                                       : new HashSet<string>(StringComparer.Ordinal);

            // Key-id fields first, then nested category classes.
            foreach (KeyEntry entry in node.Keys.OrderBy(k => k.Name, StringComparer.Ordinal))
            {
                string member = UniqueIdentifier(entry.Name, "key", used);
                AppendSummary(sb, indent, entry.Description);
                sb.Append(indent)
                  .Append("public static readonly Guid ")
                  .Append(member)
                  .Append(" = new Guid(\"")
                  .Append(entry.Id.ToString())
                  .Append("\");\n");
            }

            bool first = node.Keys.Count == 0;
            foreach (KeyValuePair<string, Node> child in node.Children)
            {
                if (!first) sb.Append('\n');
                first = false;
                string className = UniqueIdentifier(child.Key, "category", used);
                sb.Append(indent).Append("public static class ").Append(className).Append('\n');
                sb.Append(indent).Append("{\n");
                AppendNode(sb, child.Value, level + 1, seedReserved: false);
                sb.Append(indent).Append("}\n");
            }
        }

        private static void AppendTranslations(StringBuilder sb, int level, List<string> languages,
                                               List<LocLocalizationKey> keys, LocProject project)
        {
            string i0 = Indent(level);
            string i1 = Indent(level + 1);
            string i2 = Indent(level + 2);

            sb.Append(i0).Append("/// <summary>All exported translations, keyed by language then key id.</summary>\n");
            sb.Append(i0)
              .Append("public static readonly Dictionary<string, Dictionary<Guid, string>> Translations = new Dictionary<string, Dictionary<Guid, string>>\n");
            sb.Append(i0).Append("{\n");

            foreach (string lang in languages)
            {
                sb.Append(i1).Append("{ ").Append(ToLiteral(lang)).Append(", new Dictionary<Guid, string>\n");
                sb.Append(i1).Append("{\n");
                foreach (LocLocalizationKey key in keys)
                {
                    LocKeyTranslation? translation = key.Translations.Find(t => t.LanguageId == lang);
                    string             text        = translation?.Text ?? string.Empty;
                    sb.Append(i2)
                      .Append("{ new Guid(\"")
                      .Append(key.Id.ToString())
                      .Append("\"), ")
                      .Append(ToLiteral(text))
                      .Append(" },\n");
                }
                sb.Append(i1).Append("} },\n");
            }

            sb.Append(i0).Append("};\n");
        }

        private static void AppendGetMethod(StringBuilder sb, int level)
        {
            string i0 = Indent(level);
            string i1 = Indent(level + 1);
            string i2 = Indent(level + 2);

            sb.Append(i0).Append("/// <summary>\n");
            sb.Append(i0).Append("/// Returns the translation for <paramref name=\"keyId\"/> in <paramref name=\"language\"/>,\n");
            sb.Append(i0).Append("/// or an empty string when it is missing. When <paramref name=\"values\"/> is supplied the\n");
            sb.Append(i0).Append("/// text is rendered through SmartFormat; otherwise the raw text is returned.\n");
            sb.Append(i0).Append("/// </summary>\n");
            sb.Append(i0).Append("public static string Get(string language, Guid keyId, IDictionary<string, object>? values = null)\n");
            sb.Append(i0).Append("{\n");
            sb.Append(i1).Append("if (!Translations.TryGetValue(language, out Dictionary<Guid, string>? langMap) || langMap == null)\n");
            sb.Append(i2).Append("return string.Empty;\n");
            sb.Append(i1).Append("if (!langMap.TryGetValue(keyId, out string? text) || text == null)\n");
            sb.Append(i2).Append("return string.Empty;\n");
            sb.Append(i1).Append("return values == null ? text : Smart.Format(text, values);\n");
            sb.Append(i0).Append("}\n");
        }

        private static void AppendSummary(StringBuilder sb, string indent, string description)
        {
            if (string.IsNullOrWhiteSpace(description)) return;

            string   escaped = SecurityElement.Escape(description) ?? description;
            string[] lines   = escaped.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');

            if (lines.Length == 1)
            {
                sb.Append(indent).Append("/// <summary>").Append(lines[0]).Append("</summary>\n");
                return;
            }

            sb.Append(indent).Append("/// <summary>\n");
            foreach (string line in lines)
                sb.Append(indent).Append("/// ").Append(line).Append('\n');
            sb.Append(indent).Append("/// </summary>\n");
        }

        // ── Tree ────────────────────────────────────────────────────────────

        private static Node BuildTree(LocProject project, List<LocLocalizationKey> keys)
        {
            Node root = new Node();
            foreach (LocLocalizationKey key in keys)
            {
                Node node = root;
                foreach (string catName in CategoryPath(key, project))
                {
                    if (!node.Children.TryGetValue(catName, out Node? child))
                    {
                        child = new Node();
                        node.Children.Add(catName, child);
                    }
                    node = child;
                }
                node.Keys.Add(new KeyEntry(key.KeyName, key.Id, key.Description));
            }
            return root;
        }

        private static List<string> CategoryPath(LocLocalizationKey key, LocProject project)
        {
            List<string> parts   = new List<string>();
            LocCategory? current = project.Categories.Find(c => c.Id == key.CategoryId);

            // Depth cap guards against a malformed parent cycle.
            int guard = 0;
            while (current != null && guard++ < 256)
            {
                parts.Insert(0, current.Name);
                if (current.ParentCategoryId == null) break;
                current = project.Categories.Find(c => c.Id == current.ParentCategoryId);
            }
            return parts;
        }

        private static List<LocLocalizationKey> OrderedExportedKeys(LocProject project, LocExportOptions? options)
        {
            IEnumerable<LocLocalizationKey> keys = project.Keys;
            if (options != null)
                keys = keys.Where(k => LocalizationExportService.PassesFilter(k, options));
            return keys.OrderBy(k => LocalizationExportService.FullKeyName(k, project)).ToList();
        }

        // ── Identifiers & literals ──────────────────────────────────────────

        private static string UniqueIdentifier(string raw, string fallback, HashSet<string> used)
        {
            string baseId  = SanitizeIdentifier(raw, fallback);
            string escaped = EscapeKeyword(baseId);

            // Dedupe on the bare identifier so "@class" and "class" can't both land in a scope.
            string candidate = escaped;
            int    suffix    = 2;
            while (!used.Add(StripAt(candidate)))
            {
                candidate = EscapeKeyword(baseId + "_" + suffix.ToString(CultureInfo.InvariantCulture));
                suffix++;
            }
            return candidate;
        }

        private static string SanitizeIdentifier(string raw, string fallback)
        {
            if (string.IsNullOrEmpty(raw)) return fallback;

            StringBuilder sb = new StringBuilder(raw.Length);
            for (int i = 0; i < raw.Length; ++i)
            {
                char c  = raw[i];
                bool ok = i == 0
                              ? char.IsLetter(c) || c == '_'
                              : char.IsLetterOrDigit(c) || c == '_';
                sb.Append(ok ? c : '_');
            }

            string id = sb.ToString();
            if (id.Length == 0) return fallback;
            if (!(char.IsLetter(id[0]) || id[0] == '_'))
                id = "_" + id;
            return id;
        }

        private static string SanitizeNamespace(string raw)
        {
            string[] parts = raw.Split('.');
            for (int i = 0; i < parts.Length; ++i)
                parts[i] = EscapeKeyword(SanitizeIdentifier(parts[i], "_"));
            return string.Join(".", parts);
        }

        private static string EscapeKeyword(string id) => _CSharpKeywords.Contains(id) ? "@" + id : id;

        private static string StripAt(string id) => id.Length > 0 && id[0] == '@' ? id.Substring(1) : id;

        private static string ToLiteral(string s)
        {
            StringBuilder sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (char c in s)
            {
                switch (c)
                {
                    case '"':  sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\r': sb.Append("\\r");  break;
                    case '\n': sb.Append("\\n");  break;
                    case '\t': sb.Append("\\t");  break;
                    default:
                        if (c < 0x20)
                            sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        else
                            sb.Append(c);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        private static string Indent(int level)
        {
            StringBuilder sb = new StringBuilder(level * _INDENT.Length);
            for (int i = 0; i < level; ++i)
                sb.Append(_INDENT);
            return sb.ToString();
        }

        private static readonly HashSet<string> _CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while",
        };

        private sealed class Node
        {
            public SortedDictionary<string, Node> Children { get; } =
                new SortedDictionary<string, Node>(StringComparer.Ordinal);

            public List<KeyEntry> Keys { get; } = new List<KeyEntry>();
        }

        private readonly struct KeyEntry
        {
            public KeyEntry(string name, Guid id, string description)
            {
                Name        = name;
                Id          = id;
                Description = description;
            }

            public string Name        { get; }
            public Guid   Id          { get; }
            public string Description { get; }
        }
    }
}
