// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically by Deusald Localizer.
//     Any changes made to this file may be lost when it is regenerated.
//
//     'Localization.Get' formats values through SmartFormat, so the
//     consuming project must reference the SmartFormat NuGet package.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SmartFormat;

#nullable enable

namespace DeusaldLocalizerWeb
{
    public static class Localization
    {
        public static class Home
        {
            public static readonly Guid subtitle = new Guid("1a3055ee-b21f-4469-8278-705f66941544");
        }

        /// <summary>All exported translations, keyed by language then key id.</summary>
        public static readonly Dictionary<string, Dictionary<Guid, string>> Translations = new Dictionary<string, Dictionary<Guid, string>>
        {
            { "en-US", new Dictionary<Guid, string>
            {
                { new Guid("1a3055ee-b21f-4469-8278-705f66941544"), "Translate your game, together." },
            } },
        };

        /// <summary>
        /// Returns the translation for <paramref name="keyId"/> in <paramref name="language"/>,
        /// or an empty string when it is missing. When <paramref name="values"/> is supplied the
        /// text is rendered through SmartFormat; otherwise the raw text is returned.
        /// </summary>
        public static string Get(string language, Guid keyId, IDictionary<string, object>? values = null)
        {
            if (!Translations.TryGetValue(language, out Dictionary<Guid, string>? langMap) || langMap == null)
                return string.Empty;
            if (!langMap.TryGetValue(keyId, out string? text) || text == null)
                return string.Empty;
            return values == null ? text : Smart.Format(text, values);
        }
    }
}
